
services:
  notificator:
    container_name: "notificator"
    build: 
      context: .
      dockerfile: docker/Dockerfile
    command: ["poetry", "run", "python", "main.py"]

    volumes:
    - /var/www/stager2_tura_usr/data/www/stager2.turan-soft.ru/storage/logs:/logs